[hosts.xps17-nixos]
network = "tailc585e.ts.net"
ip_addr = "192.168.4.105"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAccbgX9JOk+fFGw36pMszoIh2Clh9NQyRml9GX692vC"
tailscale = "100.111.21.45"

[hosts.optiplex-nixos]
network = "tailc585e.ts.net"
ip_addr = "137.99.128.114"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6O0OeAVYRMvydK7KA8OrF2oBHxh6woQ03EzEQ87OfC"
tailscale = "100.122.39.78"

[hosts.macmini-darwin]
network = "tailc585e.ts.net"
ip_addr = "137.99.128.105"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBQtZsTzvsBJwoTKWrjlrWVX3L7uMOT/oZFwaihazKYd"
tailscale = "100.75.193.90"

# [hosts.win-wsl]
# network = "tailc585e.ts.net"
# ip_addr = ""
# ssh_pubkey = ""
# tailscale = ""
