name: "CI"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: jedimaster
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix flake check

  nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixosConfiguration:
          - xps17-nixos
          - optiplex-nixos
          - win-wsl
    steps:
    - run: sudo apt-get clean
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: jedimaster
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix -Lv build ".#nixosConfigurations.${{ matrix.nixosConfiguration }}.config.system.build.toplevel"

